version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 15432:5432
  redis:
    image: redis:latest
    ports:
      - 16380:6380
