name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths-ignore:
      - ".editorconfig"
      - ".gitattributes"
      - ".gitignore"
      - ".dockerignore"
      - "*.config"
      - "*.md"
      - ".github/*.yml"
      - "middleware/**"
      - ".vscode/**"
jobs:
  ci:
    runs-on: ubuntu-latest
    name: CI
    if: github.event.pull_request.merged == true || github.event.action != 'closed'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"
      - name: Build configs
        shell: bash
        run: mvn --batch-mode install -am -pl build-tools/configs -Pci
      - name: Install libraries and extensions
        shell: bash
        run: mvn --batch-mode install -DskipTests=true -DskipApps=trues -Pci
      - name: Coding style check
        shell: bash
        run: mvn --batch-mode spotless:check checkstyle:check spotbugs:check -Pci -pl '!coverage'
      - name: Test
        shell: bash
        run: mvn --batch-mode test -Pci
